version: '3'
services:
  sonar:
    build: ./sonar
    depends_on:
      - api
      - ui
      - proxy
  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./secret:/secret
      - /Users/charliem/workspace/artifact-service/v1/artifacts/reports:/artifacts
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - LITELLM_LOG=WARNING
      - CONFIG_PATH=run_configs/default.json
      - ARTIFACT_OUTPUT_DIR=/artifacts
    ports:
      - 8000:8000
    env_file:
      - .env
  watcher:
    build: ./api
    entrypoint: ["python", "-m", "scholarqa.watcher_main"]
    volumes:
      - ./api:/api
      - ./secret:/secret
      - /Users/charliem/workspace/artifact-service/v1/artifacts/reports:/artifacts
    environment:
      - PYTHONUNBUFFERED=1
      - LITELLM_LOG=WARNING
      - CONFIG_PATH=run_configs/default.json
      - ARTIFACT_OUTPUT_DIR=/artifacts
      - PYTHONPATH=/api
    env_file:
      - .env
    depends_on:
      - api
  ui:
    build: ./ui
    # We can't mount the entire UI directory, since JavaScript dependencies
    # (`node_modules`) live at that location.
    volumes:
      - ./ui/src:/ui/src
      - ./ui/public:/ui/public
      - ./ui/package.json:/ui/package.json
      - ./ui/yarn.lock:/ui/yarn.lock
      - ./ui/tsconfig.json:/ui/tsconfig.json
    environment:
      - NODE_ENV=development
    ports:
      - 4000:3000
  proxy:
    build: ./proxy
    ports:
      - 8080:8080
    depends_on:
      - ui
      - api
